In [6]:
#NUMPY as library used in data science

import numpy as np
print("numpy imported")

numpy imported


In [9]:
## Array creation

ls = [25,14,36,78,46,98,758,79,665,55]
arr = np.array(ls)
arr

array([ 25,  14,  36,  78,  46,  98, 758,  79, 665,  55])

In [6]:
type(arr)

## nd == n dimensional array

numpy.ndarray

In [7]:
#list created simply

ls2 = [25,'upflairs',True,34.2]
ls2

[25, 'upflairs', True, 34.2]

In [10]:
#float value in nunpy :- in list if one value is float than whole list written as float value

ls = [25,14,36,78,46,98,758,79,665,55,100.25]
arr = np.array(ls)
arr

array([ 25.  ,  14.  ,  36.  ,  78.  ,  46.  ,  98.  , 758.  ,  79.  ,
       665.  ,  55.  , 100.25])

In [11]:
#string value in nunpy :- in list if one value is string than whole list written as string value

ls = [25,14,36,78,46,98,758,79,665,55,'upflairs']
arr = np.array(ls)
arr

array(['25', '14', '36', '78', '46', '98', '758', '79', '665', '55',
       'upflairs'], dtype='<U21')

In [7]:
ls = [25,14,36,78,46,98,758,79,665,55]
arr = np.array(ls)
arr

array([ 25,  14,  36,  78,  46,  98, 758,  79, 665,  55])

In [19]:
# to count lenght or size in list

len(arr)

10

In [20]:
arr.size   # or len(arr)

10

In [23]:
arr.dtype

dtype('<U21')

In [27]:
#list startin and stoping point

arr[1:]

array([ 14,  36,  78,  46,  98, 758,  79, 665,  55])

In [28]:
arr[7:]

array([ 79, 665,  55])

In [31]:
arr[-3:]

array([ 79, 665,  55])

In [39]:
arr[::-1]

array([ 55, 665,  79, 758,  98,  46,  78,  36,  14,  25])

In [3]:
#list :- arange in descending order by startin and stoping point as in sequntial

np.arange(1,60)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59])

In [4]:
arr2=np.arange(60)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [5]:
arr2=np.arange(0,101,2)       # range(startin,stoping,jumping)
arr2

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [6]:
len(arr2)

51

In [7]:
# to craete multiple same  values as we give commands 

np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.linspace(1,50,10)    # in bettween 1 to 50 , item 20

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [12]:
arr = np.random.randint(1,300,500)   # in between 1 - 300 items ==> 500
arr

array([254,  90, 123, 234, 121,  93, 158, 266, 175,  85,  39, 185, 227,
        82,  87,  66,  73,  40, 103, 240,  11, 296,  28, 205,  10, 155,
       161, 219, 113, 225, 179, 143, 172, 216,  42, 298,  95, 240, 213,
        57,  22,  78, 185, 184, 171,  83,  93,  40, 294, 292, 218, 136,
        14, 269, 121, 155, 224, 262, 118,  39, 119,  88, 286, 150, 291,
       129, 197, 266, 291,  59,  40, 121,   1, 126, 162,   8, 100, 142,
        79,  14, 284, 206, 253, 142, 293, 122,  22,  97, 134, 292, 102,
       273, 195,  27, 183, 282, 128, 233, 214,  43,  62,  81,   1,  89,
       251,  28, 257,   7,  47, 289, 157,  20, 214, 220, 166, 219,  71,
       287, 157, 249, 178, 224, 152, 241, 268, 176, 146, 292, 120, 175,
       258, 178,  94, 265, 284, 100, 117, 199, 208,   1,  63,  13, 283,
       152,  11,  74, 193, 195, 140, 281, 204, 262,  72, 138, 225, 225,
        13,  54, 179, 140, 171, 185,  31, 217, 202, 183, 263, 287, 147,
       299, 206,  48, 218, 274,  42, 238,  99, 164, 228,  14, 11

In [13]:
arr.size

500

In [34]:
#for loop in numpy

count=0
for item in arr:
    if item <= 70:
        count +=1
        print(item)
print("no of item: ",count)

39
66
40
11
28
10
42
57
22
40
14
39
59
40
1
8
14
22
27
43
62
1
28
7
47
20
1
63
13
11
13
54
31
48
42
14
16
24
55
61
67
8
19
46
51
32
66
47
30
63
10
31
1
50
37
19
61
48
67
3
15
61
58
68
56
68
52
60
44
18
19
13
47
12
52
13
14
31
22
43
31
40
18
70
35
8
11
12
68
49
11
23
3
13
50
37
15
32
37
34
69
60
3
11
20
42
30
14
7
20
19
11
44
8
16
no of item:  115


In [35]:
arr[arr<=70]

array([39, 66, 40, 11, 28, 10, 42, 57, 22, 40, 14, 39, 59, 40,  1,  8, 14,
       22, 27, 43, 62,  1, 28,  7, 47, 20,  1, 63, 13, 11, 13, 54, 31, 48,
       42, 14, 16, 24, 55, 61, 67,  8, 19, 46, 51, 32, 66, 47, 30, 63, 10,
       31,  1, 50, 37, 19, 61, 48, 67,  3, 15, 61, 58, 68, 56, 68, 52, 60,
       44, 18, 19, 13, 47, 12, 52, 13, 14, 31, 22, 43, 31, 40, 18, 70, 35,
        8, 11, 12, 68, 49, 11, 23,  3, 13, 50, 37, 15, 32, 37, 34, 69, 60,
        3, 11, 20, 42, 30, 14,  7, 20, 19, 11, 44,  8, 16], dtype=int32)

In [36]:
arr[arr<=70].size        ## using numpy

115

In [8]:
arr.ndim  #n dimensional procedure

1

In [9]:
## <<< 2D array ...>>>> async

arr

array([ 25,  14,  36,  78,  46,  98, 758,  79, 665,  55])

In [10]:
# 2D [1D,1D,1D,1D]

lst=[[1,2,3],[4,5,6],[7,8,9]]
type(lst)

list

In [11]:
import numpy as np

In [12]:
arr = np.array(lst)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
arr.shape     # (row,column)

(3, 3)

In [14]:
arr.ndim

2

In [15]:
arr[0]

array([1, 2, 3])

In [16]:
arr[1]

array([4, 5, 6])

In [17]:
arr[2]    # single row

array([7, 8, 9])

In [18]:
arr[0:2]     # multiple row

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
arr[1:3 ,1:3]

array([[5, 6],
       [8, 9]])

In [32]:
#for random array representing

arr2=np.random.randint(1,200,(10,6))
arr2

array([[ 42,  77,   7, 140, 138, 165],
       [ 39, 176,  24, 144,  34,  32],
       [ 34, 146,  31, 196,  97, 176],
       [114,   2, 162,  27,  42,  54],
       [ 90,  29,  17,  20, 177, 111],
       [ 27, 140,  59,  76, 195,  92],
       [182,  10, 139,  10, 113, 119],
       [178,  64,  54, 109,  99, 124],
       [ 53, 146,  17, 179, 104,  74],
       [ 26,  83,  88, 191, 126,  28]], dtype=int32)

In [26]:
arr2[4:9]

array([[123,  46, 123,  37, 135,  24],
       [ 83,  99,  10, 110, 151,  76],
       [103,  85,  23, 181, 120,  55],
       [ 74,  49,  72, 179, 178, 140],
       [118, 169,  56, 151, 179, 173]], dtype=int32)

In [27]:
arr2[4:9,3:6]

array([[ 37, 135,  24],
       [110, 151,  76],
       [181, 120,  55],
       [179, 178, 140],
       [151, 179, 173]], dtype=int32)

In [30]:
arr2[:,1:3]

array([[ 32, 144],
       [185,   9],
       [143, 115],
       [129,  80],
       [ 46, 123],
       [ 99,  10],
       [ 85,  23],
       [ 49,  72],
       [169,  56],
       [164, 151]], dtype=int32)

In [38]:
arr2[-6:-1,-3:]

array([[ 20, 177, 111],
       [ 76, 195,  92],
       [ 10, 113, 119],
       [109,  99, 124],
       [179, 104,  74]], dtype=int32)

In [40]:
arr2[::-1,::-1]

array([[ 28, 126, 191,  88,  83,  26],
       [ 74, 104, 179,  17, 146,  53],
       [124,  99, 109,  54,  64, 178],
       [119, 113,  10, 139,  10, 182],
       [ 92, 195,  76,  59, 140,  27],
       [111, 177,  20,  17,  29,  90],
       [ 54,  42,  27, 162,   2, 114],
       [176,  97, 196,  31, 146,  34],
       [ 32,  34, 144,  24, 176,  39],
       [165, 138, 140,   7,  77,  42]], dtype=int32)

In [41]:
arr2[-6:-4,-6:-4]

array([[ 90,  29],
       [ 27, 140]], dtype=int32)

In [44]:
arr2[-1:,-1:]

array([[28]], dtype=int32)

In [45]:
arr2[-1,-1]=1000

In [46]:
arr2[-1,-1]

np.int32(1000)

In [47]:
arr2

array([[  42,   77,    7,  140,  138,  165],
       [  39,  176,   24,  144,   34,   32],
       [  34,  146,   31,  196,   97,  176],
       [ 114,    2,  162,   27,   42,   54],
       [  90,   29,   17,   20,  177,  111],
       [  27,  140,   59,   76,  195,   92],
       [ 182,   10,  139,   10,  113,  119],
       [ 178,   64,   54,  109,   99,  124],
       [  53,  146,   17,  179,  104,   74],
       [  26,   83,   88,  191,  126, 1000]], dtype=int32)

In [52]:
arr2[0,3]=5000

In [53]:
arr2

array([[  42,   77,    7, 5000,  138,  165],
       [  39,  176,   24,  144,   34,   32],
       [  34,  146,   31,  196,   97,  176],
       [ 114,    2,  162,   27,   42,   54],
       [  90,   29,   17,   20,  177,  111],
       [  27,  140,   59,   76,  195,   92],
       [ 182,   10,  139,   10,  113,  119],
       [ 178,   64,   54,  109,   99,  124],
       [  53,  146,   17,  179,  104,   74],
       [  26,   83,   88,  191,  126, 1000]], dtype=int32)

In [54]:
arr2[-10,-3]=500

In [55]:
arr2

array([[  42,   77,    7,  500,  138,  165],
       [  39,  176,   24,  144,   34,   32],
       [  34,  146,   31,  196,   97,  176],
       [ 114,    2,  162,   27,   42,   54],
       [  90,   29,   17,   20,  177,  111],
       [  27,  140,   59,   76,  195,   92],
       [ 182,   10,  139,   10,  113,  119],
       [ 178,   64,   54,  109,   99,  124],
       [  53,  146,   17,  179,  104,   74],
       [  26,   83,   88,  191,  126, 1000]], dtype=int32)

In [56]:
arr2[0][3]=8000
arr2

array([[  42,   77,    7, 8000,  138,  165],
       [  39,  176,   24,  144,   34,   32],
       [  34,  146,   31,  196,   97,  176],
       [ 114,    2,  162,   27,   42,   54],
       [  90,   29,   17,   20,  177,  111],
       [  27,  140,   59,   76,  195,   92],
       [ 182,   10,  139,   10,  113,  119],
       [ 178,   64,   54,  109,   99,  124],
       [  53,  146,   17,  179,  104,   74],
       [  26,   83,   88,  191,  126, 1000]], dtype=int32)

In [2]:
## <<<  3D..... >>>


import numpy as np


In [5]:
# 3D =[2d,2d,2d,2d]

arr3d=np.random.randint(1,200,(5,10,5))
arr3d

array([[[ 66, 125,  66, 129,  32],
        [137, 113, 101, 114,  42],
        [199,  28, 136, 120, 162],
        [ 99, 138, 139,  18,  29],
        [ 94,  52,  97, 146, 185],
        [  8, 124,  63, 140,  26],
        [ 56, 181, 150,  56, 108],
        [102, 180, 155,  21,  31],
        [135, 175,  44,  38, 130],
        [  1, 126,  39,  22, 125]],

       [[186,  11,  85, 179,  60],
        [ 84,  26,  56,  56, 110],
        [ 89, 119,   7,  59, 162],
        [121, 186, 184, 146, 138],
        [140, 109,  63, 123,  35],
        [ 92,  35,  43,  34, 143],
        [183, 106, 124,  43, 168],
        [168, 192, 104, 129, 162],
        [109, 190,  44, 151, 183],
        [173, 129,  45,  34, 141]],

       [[ 96, 177, 121, 192, 190],
        [170, 146, 135, 135, 198],
        [153,  43, 128, 158,  87],
        [ 95, 120,  74, 100, 193],
        [ 80, 180, 100,  24, 148],
        [120,  82, 195,  64, 188],
        [129, 198, 141,  98,  61],
        [196, 199,  74,  11,   7],
        [104, 11

In [6]:
arr3d.shape
#(5,10,5)
# 5 ==> tables
# 10 ==> row
# 5 ==> coloumn

(5, 10, 5)

In [7]:
arr3d.ndim

3

In [10]:
arr3d[0]      # table


array([[ 66, 125,  66, 129,  32],
       [137, 113, 101, 114,  42],
       [199,  28, 136, 120, 162],
       [ 99, 138, 139,  18,  29],
       [ 94,  52,  97, 146, 185],
       [  8, 124,  63, 140,  26],
       [ 56, 181, 150,  56, 108],
       [102, 180, 155,  21,  31],
       [135, 175,  44,  38, 130],
       [  1, 126,  39,  22, 125]], dtype=int32)

In [11]:
arr3d[0:2]       # for table

array([[[ 66, 125,  66, 129,  32],
        [137, 113, 101, 114,  42],
        [199,  28, 136, 120, 162],
        [ 99, 138, 139,  18,  29],
        [ 94,  52,  97, 146, 185],
        [  8, 124,  63, 140,  26],
        [ 56, 181, 150,  56, 108],
        [102, 180, 155,  21,  31],
        [135, 175,  44,  38, 130],
        [  1, 126,  39,  22, 125]],

       [[186,  11,  85, 179,  60],
        [ 84,  26,  56,  56, 110],
        [ 89, 119,   7,  59, 162],
        [121, 186, 184, 146, 138],
        [140, 109,  63, 123,  35],
        [ 92,  35,  43,  34, 143],
        [183, 106, 124,  43, 168],
        [168, 192, 104, 129, 162],
        [109, 190,  44, 151, 183],
        [173, 129,  45,  34, 141]]], dtype=int32)

In [14]:
arr3d[1,6:]

array([[183, 106, 124,  43, 168],
       [168, 192, 104, 129, 162],
       [109, 190,  44, 151, 183],
       [173, 129,  45,  34, 141]], dtype=int32)

In [15]:
arr3d[0:,6:]

array([[[ 56, 181, 150,  56, 108],
        [102, 180, 155,  21,  31],
        [135, 175,  44,  38, 130],
        [  1, 126,  39,  22, 125]],

       [[183, 106, 124,  43, 168],
        [168, 192, 104, 129, 162],
        [109, 190,  44, 151, 183],
        [173, 129,  45,  34, 141]],

       [[129, 198, 141,  98,  61],
        [196, 199,  74,  11,   7],
        [104, 114,  73, 156,  50],
        [  5,  51,  83, 135, 120]],

       [[104, 139,  49,  58,  74],
        [ 14, 150, 165, 188,  48],
        [  6, 130,  40,  55,  32],
        [182,  40,  85,  62,  81]],

       [[177,  84,  39, 184, 195],
        [ 95,  13, 158,  46, 188],
        [147, 168,  47,   9, 103],
        [ 67, 111, 142,  51, 165]]], dtype=int32)

In [16]:
arr3d[0:,-1:]

array([[[  1, 126,  39,  22, 125]],

       [[173, 129,  45,  34, 141]],

       [[  5,  51,  83, 135, 120]],

       [[182,  40,  85,  62,  81]],

       [[ 67, 111, 142,  51, 165]]], dtype=int32)

In [18]:
arr3d[4,-1,-1]=500
arr3d

array([[[ 66, 125,  66, 129,  32],
        [137, 113, 101, 114,  42],
        [199,  28, 136, 120, 162],
        [ 99, 138, 139,  18,  29],
        [ 94,  52,  97, 146, 185],
        [  8, 124,  63, 140,  26],
        [ 56, 181, 150,  56, 108],
        [102, 180, 155,  21,  31],
        [135, 175,  44,  38, 130],
        [  1, 126,  39,  22, 125]],

       [[186,  11,  85, 179,  60],
        [ 84,  26,  56,  56, 110],
        [ 89, 119,   7,  59, 162],
        [121, 186, 184, 146, 138],
        [140, 109,  63, 123,  35],
        [ 92,  35,  43,  34, 143],
        [183, 106, 124,  43, 168],
        [168, 192, 104, 129, 162],
        [109, 190,  44, 151, 183],
        [173, 129,  45,  34, 141]],

       [[ 96, 177, 121, 192, 190],
        [170, 146, 135, 135, 198],
        [153,  43, 128, 158,  87],
        [ 95, 120,  74, 100, 193],
        [ 80, 180, 100,  24, 148],
        [120,  82, 195,  64, 188],
        [129, 198, 141,  98,  61],
        [196, 199,  74,  11,   7],
        [104, 11

In [22]:
arr=np.arange(60)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [23]:
arr.reshape(20,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44],
       [45, 46, 47],
       [48, 49, 50],
       [51, 52, 53],
       [54, 55, 56],
       [57, 58, 59]])

In [27]:
arr2 = arr.reshape(2,15,2)

In [29]:
arr2

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39],
        [40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49],
        [50, 51],
        [52, 53],
        [54, 55],
        [56, 57],
        [58, 59]]])

In [28]:
arr2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [31]:
arr2.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [34]:
arr=np.random.randint(1,200,(5,3))
arr

array([[132,  26,  34],
       [113, 129,  63],
       [129, 102, 192],
       [134,  29,  19],
       [113, 148, 162]], dtype=int32)

In [35]:
arr.shape

(5, 3)

In [36]:
np.transpose(arr)      # row change into coloumn and coloumn change into row

array([[132, 113, 129, 134, 113],
       [ 26, 129, 102,  29, 148],
       [ 34,  63, 192,  19, 162]], dtype=int32)

In [38]:
arr.T      # short form of transpose function

array([[132, 113, 129, 134, 113],
       [ 26, 129, 102,  29, 148],
       [ 34,  63, 192,  19, 162]], dtype=int32)

In [37]:
arr.shape

(5, 3)

In [39]:
#to convert 3d into 0ne dimensional

arr2=arr.ravel()
arr2

array([132,  26,  34, 113, 129,  63, 129, 102, 192, 134,  29,  19, 113,
       148, 162], dtype=int32)

In [40]:
arr.min()                           #min value

np.int32(19)

In [41]:
arr.max()                             #max value

np.int32(192)

In [42]:
arr.mean()                        #average

np.float64(101.66666666666667)

In [44]:
np.median(arr2)                      #average

np.float64(113.0)

In [45]:
arr = np.array([9,7,8])
arr

array([9, 7, 8])

In [48]:
arr.argmin()    # this is show acc. to (0,1,2,3) like that   ### index value show (or position)

np.int64(1)

In [49]:
arr.argmax()    ## same as argmin

np.int64(0)

In [51]:
arr.sort()      ## assending order 
arr

array([7, 8, 9])

In [52]:
arr[::-1]           # desending with the help of reverse

array([9, 8, 7])

In [53]:
arr.argsort()       ##(7,8,9)

array([0, 1, 2])